### ISSUE TITLE
是否考虑添加自定义分享链接？这个项目拉下来yarn装不上

### ISSUE THREAD

**Issue by cnscorpions** [liuguanhua/react-share-components#3]
OS:
win10 pro
node v12.13.0
npm 6.14.5
yarn 1.22.4
windows terminal

显示copy plugin，一直占用（项目该删，没有截图😂）

**Comment by liuguanhua** [comment]
@cnscorpions url属性就是定义的分享链接。更改镜像能装上吗?

**Comment by cnscorpions** [comment]
我指的是sites中的邮箱分享之类，

更改镜像指的是淘宝还源么？那我有换源，也有代理的

**Comment by liuguanhua** [comment]
可以使用children，[参考](https://github.com/liuguanhua/react-share-components/blob/master/src/ReactShareComponents.tsx#L240)，自动会加在其后面。还是意思是点击sites中属性图标执行自定义操作呢。 如果还是安装不了，最好截下图，我后面用windows试一下。

**Comment by cnscorpions** [comment]
我说的问题使用children能很好解决了，安装的话，不用自己拉下来开发了，就关了哈😁
